pipeline {
    agent {
        docker {
            image 'ruby'
            agrs '--network rocklov-network'
        }
    }
    
    stages {
        stage('Prep') {
            steps {
                sh 'cd api && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd api && rspec'
            }   
        }   
    }  
}  